Repository kvhnuke/etherwallet, pull requests merged in 2018-03, with the labels that each got.

#1621 Generate a docker image
  .dockerignore
  Dockerfile
Labels: 3_good to go

#1619 Manual gas limits for upcoming WHO token
  app/scripts/customGas.js
Labels: 3_on hold, x_token sale stuff

#1555 Add PUC eth abi
  app/scripts/abiDefinitions/ethAbi.json
Labels: x_issue: low popularity, x_token sale stuff
